[package]
name = "b2t80s_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rfd = "0.17.2"
tokio = { version = "1.53.1", features = ["full"] }
iced = { version = "0.14", features = [
    "image",
    "tokio",
    "debug",
] }
cpal = "0.18.2"
anyhow = "1.0.104"
image = { version = "0.25.10", default-features = false, features = ["png"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["NSApplication", "NSImage"] }
objc2-foundation = { version = "0.3.2", default-features = false, features = ["NSData"] }

[profile.release]
debug = false

[profile.dev]
opt-level = 1
