[package]
name = "b2t80s_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
minifb = "0.25.0"
rand = "0.8"

[profile.release]
debug = false
